### ISSUE TITLE
Silentskies: Brushplacement bugs

### ISSUE THREAD

**Issue by Xufe** [ZPSNMRiHIssues/zpsissues#100]
![2013-06-23_00002](https://f.cloud.github.com/assets/4218595/692691/235d259a-dc40-11e2-9309-6f1a12579d29.jpg)

Playerclip missplaced

![2013-06-23_00003](https://f.cloud.github.com/assets/4218595/692692/2c7e5b58-dc40-11e2-92e0-9c9df3730a12.jpg)

Door interacts with pipes

![2013-06-23_00004](https://f.cloud.github.com/assets/4218595/692693/3f4249de-dc40-11e2-9923-bfee83f7c27b.jpg)

Missing texture elevator floor ( Z spawn)

![2013-06-23_00005](https://f.cloud.github.com/assets/4218595/692695/5b6dab94-dc40-11e2-8e5a-cc58d4397778.jpg)

Water from ATC tower bottom, bad water texture+ texture missing

**Comment by SiggyWiggyWoo** [comment]
Thanks, all fixed.
