### ISSUE TITLE
Invisible keycard

### ISSUE THREAD

**Issue by Deliux** [ZPSNMRiHIssues/zpsissues#101]
Looking from the front side to zombie holding keycard becomes invisible.
![2013-06-09_00002](https://f.cloud.github.com/assets/3256637/692698/8f8a9df6-dc40-11e2-97b6-03c44e939441.jpg)

**Comment by Smil3yRiley** [comment]
Is this reproducible? Is this on the public build?

**Comment by Deliux** [comment]
It was cought in PT. Don't know if it's reproducible, maybe it's only a glich. :/

**Comment by SiggyWiggyWoo** [comment]
The keycard is very thin, else I don't know what's up. Alpha sorting issue maybe, can't do anything about it. But if it always happens then something is wrong.
