### ISSUE TITLE
Zomboeing Texturebugs

### ISSUE THREAD

**Issue by Xufe** [ZPSNMRiHIssues/zpsissues#102]
![2013-06-23_00006](https://f.cloud.github.com/assets/4218595/692696/7148262e-dc40-11e2-8f35-e6b92751b47b.jpg)
Boeing model has missing textures from inside

![2013-06-23_00007](https://f.cloud.github.com/assets/4218595/692697/8282a9d2-dc40-11e2-873e-c3da7c077119.jpg)
 Band conveyor has missaligned textures ( also moving against the moving direction)

![2013-06-23_00008](https://f.cloud.github.com/assets/4218595/692701/b9c71b62-dc40-11e2-9d23-656defe8a669.jpg)
Missing texture of the turbine sheets.

![2013-06-23_00009](https://f.cloud.github.com/assets/4218595/692702/c7fc8a78-dc40-11e2-835a-ebb1f06822ae.jpg)

Missaligned texture, beside not fitting the theme.

**Comment by Smil3yRiley** [comment]
Closing ticket to help organize tracker
