### ISSUE TITLE
(code) Switching weapons while climbing ladders will drain stamina

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#103]
If you climb up a ladder and switch weapons over and over, the game will think you're jumping; you can drain your entire stamina with this method.

---

Steps to Reproduce
1) Climb up a ladder
2) Switch between your melee and starting pistol

**Comment by xerox8521** [comment]
Same thing works if you fall down from any range while you are in the air you switch the guns and get slowed and your stamina bar gets reduced. This might reduce the fall damage too
