### ISSUE TITLE
AK-47 or AK-74 - Wrong Name or Weapon

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#104]
http://cloud-2.steampowered.com/ugc/633036385773156333/81190A11256FA93C38E5D22CD41B1335379A919D/

Screenshot explains all. This weapon is supposed to be an AK-47. On HUD it shows AK-74

**Comment by Smil3yRiley** [comment]
If you REALLY want to be technical, it's actually a Type 56 rifle =P

Either way it was a minor goof up when we were making the HUD, will probably be corrected in the near future
