### ISSUE TITLE
Number of zombie maxragdolls "not working".

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#11]
As you can see, i set only 10 ragdolls, but in-game shows more than 10.
![2013-04-06_00001](https://f.cloud.github.com/assets/4042019/347699/09397056-9eec-11e2-92d5-797f4d3587ec.jpg)

**Comment by Smil3yRiley** [comment]
Did you set that value while in game, or when you were in the main menu?

**Comment by Tabajara77** [comment]
I set that yesterday, and still showing more ragdolls. Idk why.

Edit: In 10.0000, the map was with 15 ragdolls, and after one zombie die, one dead body gone.

**Comment by Smil3yRiley** [comment]
In the dev build, I set my max zombie ragdoll count to 3 and it worked as intended
