### ISSUE TITLE
(code) UI sizing issues in Source SDK 2013

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#110]
Certain hud elements are stretched or are improperly resized in the game: The scoreboard, and voice chat (whenever someone talks) icons are a few of them.

**Comment by SammyROCK** [comment]
Scoreboard got fixed.
I'll need a screenshot of the voice chat one.

**Comment by SiggyWiggyWoo** [comment]
Screenshot of the voice icon:

![image2342342341](https://f.cloud.github.com/assets/4086421/935450/4797d15e-0084-11e3-869a-9efde10d0855.jpg)
