### ISSUE TITLE
(code) Missing sounds in Source SDK 2013

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#111]
As a result of the SDK 2013 port, some sounds are missing: Currently there's no weapon pickup sound (the ammo pick up sound works), and no pain sounds.

If you find any other missing sounds, please mention what they are!

**Comment by Tabajara77** [comment]
And no Survivor's Intro sound, when the round starts, one of the survivors talk something like "Who was the stupid ass idea to come here any way" from Jennifer.
