### ISSUE TITLE
(code) Missing materials in Source SDK 2013

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#112]
As a result of the SDK 2013 port, certain materials are missing in the game. Zombie vision is one of the most noticeable  issues, but there are others located through the game (apparently when going to a zpo map, some testers have a massive missing texture overlay? Perhaps it's tied to the objective icons?)

If you find any issues, please post them here!

**Comment by Wazanator** [comment]
I noticed a decal/overaly missing in zps_town, I'll look into it.

**Comment by SammyROCK** [comment]
Zombie vision got fixed, 2013 sdk requires materials to have references in order to be loaded, vgui elements now have a special way to declare and reference.
