### ISSUE TITLE
(code) Tweaked values in gameplay, as a result of porting to 2013

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#113]
Due to the SDK 2013 port, some gameplay values may have been unintentionally changed.

In particular, movement speeds for both human AND zombie teams have been significantly boosted.

If you notice anything different in the game, please mention these issues here!

**Comment by maisteven** [comment]
Ragdolls don't move when hitting them as a zombie.
You move as slow as a snail when crouch walking.
