### ISSUE TITLE
(ZPS DEV 2013) Most obvious bugs

### ISSUE THREAD

**Issue by 6sic6** [ZPSNMRiHIssues/zpsissues#114]
Just gonna make a list im sure most of you know them already
missing sounds including pain from zombie perspective while hitting human
zombie vision 
alt tabing causes vision to become checker board while human
zombies fail to load right skin upon death as human keeps going to marcus skin
crouch speeds and height from ground is off default speed is faster than normal

**Comment by SammyROCK** [comment]
Fixed crouch speed.
