### ISSUE TITLE
ZPSDev2013 | Multiplayer Options shows HL2's characters

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#116]
The area where you choice your survivor model, you can also see combines/citizens from HL2.

**Comment by SammyROCK** [comment]
Fixed by removing
game+mod            hl2mp/hl2mp_pak.vpk
from gameinfo.txt

Some issues may pop from this change, which then the team will need to extract the needed files from that vpk.
