### ISSUE TITLE
Server Browser 'freezing' game

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#119]
Recently some users have reported issues that their game will 'freeze' if they try to search for servers; I think I managed to replicate this bug. The video will show what happens 

http://www.youtube.com/watch?v=lWrjuiT67Nc

Basically if you try to search for servers, the game will use up 100% of your CPU to find them. As a result, the game will hang up for a random amount of time (from a few seconds, to over a minute or two)

This seems to have happened as a result of a recent Source SDK Base 2007 update

**Comment by JoelTroch** [comment]
Issue confirmed on ZPS and others Source based mods, it's not related to ZPS but the Source SDK Base 2007 update.
