### ISSUE TITLE
"Resource Limit is Reached" - In-game/Website issue

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#121]
While you're joining in the server, after 2~3 map changes, this "message" show up.
![2013-07-26_00001](https://f.cloud.github.com/assets/4042019/866376/535feec6-f671-11e2-9268-6301fe4354d7.jpg)

I think that is using the internet to always updating news/info/hints about the game right? And i never see something like that for years.

So it's a "problem" or it's normal?

**Comment by JoelTroch** [comment]
I confirm at 50% this bug.

On my side, it appears with the latest Internet Explorer's error styles, however, this doesn't happen to me after 2-3 maps change but randomly. I don't know if the issue is either on ZPS's website side or yours.

**Comment by Wazanator** [comment]
I can confirm this bug

**Comment by jonnyboy0719** [comment]
_Resource Limit is Reached_ is still happening, and has nothing to do with ZPS itself, its the provider for ZPS website that gets this issue. More info can be found here: http://client.guru-host.eu/knowledgebase/147/Resource-limit-is-reached.html
