### ISSUE TITLE
func_ladder

### ISSUE THREAD

**Issue by TheMaddog** [ZPSNMRiHIssues/zpsissues#123]
Using Source SDK Multiplayer 2013 and compiling for ZPS Dev Build.

My hammer is setup correctly and none of my func_ladders are working. Upon trying to interact with a func_ladder ingame after compiling nothing happens. It's like it's not there.

I have remade the func_ladders and I have also tried to fix the ladders by using the public builds ZPS FGD but of no success.

I leave it with the devs, I have tried everything I can possibly think of.

**Comment by Tabajara77** [comment]
func_ladder doesn't work any more on SDK 2013. Use func_usableladder instead.
