### ISSUE TITLE
zps_blackout - Missing textures room

### ISSUE THREAD

**Issue by RanmaZPS** [ZPSNMRiHIssues/zpsissues#13]
This room is missing textures: http://steamcommunity.com/sharedfiles/filedetails/?id=137574280

**Comment by Smil3yRiley** [comment]
Where exactly is this room located?

**Comment by RanmaZPS** [comment]
Room 302 on the right staircase.

**Comment by Jonny-Steel** [comment]
Yes thx, I forgot to upload these custom textures (room 302) to the DevBuild. I will fix it.

--- Bug report can be closed. ---
