### ISSUE TITLE
(code) CTD when trying to kill zombies with grenades?

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#139]
I was typing in game when I crashed to desktop, apparently Tabajara was trying to kill the Carrier with grenades when it happened (it caused everyone to crash)

I have some .mdmps here (for those who have crash files they're located in steam/dumps): 
https://dl.dropboxusercontent.com/u/972438/zps/crash%20file%20zps%208-25.zip

**Comment by Tabajara77** [comment]
My dmp file:
https://dl.dropboxusercontent.com/u/8569479/crash_hl2.exe_20130825165704_1.dmp

Edit: I throwed 2~3 granades closer to the carrier and after died, i crashed.

**Comment by Deliux** [comment]
Just running around with M4 when crashed

My mdmp file:
https://dl.dropboxusercontent.com/u/85655441/crash_hl2.exe_20130825225703_1.dmp

**Comment by Cookieandcream** [comment]
I believe Neo was trying to kill me, I was a regular zombie. 

Here it is : https://www.dropbox.com/s/wp1a5isc66e2t05/crash_hl2.exe_20130825125703_1.dmp

**Comment by neoassassin** [comment]
I was shooting Cookie when it crashed. But I think we all got an assert error before we crashed. After I clicked Always Ignore is when it crashed for me.

https://www.dropbox.com/s/qqaumsz7l20ddgy/crash_hl2.exe_20130825155705_1.dmp

**Comment by SammyROCK** [comment]
Update: Need test for potential fix.
