### ISSUE TITLE
Shiny boxes

### ISSUE THREAD

**Issue by Cookieandcream** [ZPSNMRiHIssues/zpsissues#14]
![zps_blackout0000](https://f.cloud.github.com/assets/4086414/349343/1c99fc08-9fbc-11e2-8cb1-e905e354c796.jpg)
The boxes were flashing for me when I walked by the bottom staircase. They appear shiny and bright in colour.

**Comment by Jonny-Steel** [comment]
It's not just these boxes. Several other props show us the same effect sometimes. Something is wrong with this "new" dynamic light zombie vision. In this case it's more Sammy's devison of expertise. :)
