### ISSUE TITLE
Auto Infection issue 

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#146]
When there's only one zombie, and he quit from the server, someone get a infection to be the new zombie right?
Well, i was specting and joined on the zombie team after 2 seconds, but the guy that got the infection, still didn't get "cured", so he becomes a zombie since the server was with only 4 players.

![2013-09-05_00001](https://f.cloud.github.com/assets/4042019/1093164/3b958fa8-1697-11e3-8562-fe21ff633aac.jpg)

**Comment by xerox8521** [comment]
This also happens if the infected does turn the next survivor will be infected and not cured when there are 3 players and the zombie quits

**Comment by Tabajara77** [comment]
Same guy that 'retry', he came back as a zombie and the guy that was selected to 'replace' him was still infected.

http://steamcommunity.com/sharedfiles/filedetails/?id=228144105
