### ISSUE TITLE
Players can see spectators in-game (while they're already "specting" )

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#147]
Humans could see me as a spectator (observer) while i was already "flying around" as a spec.
It's like, they could see my body.

**Comment by Wazanator** [comment]
Server name/ip? Could possibly be a conflict with a plugin

**Comment by Tabajara77** [comment]
189.1.172.19:27017 

Sidenote: Just one guy after 2 weeks of this server been up he saw me.
