### ISSUE TITLE
zps_blackout zombie spawn

### ISSUE THREAD

**Issue by xterminator1986** [ZPSNMRiHIssues/zpsissues#15]
First off the texture glitch

http://i775.photobucket.com/albums/yy40/Xterm/Steam/zps_blackout0001.jpg

Secondly, i did a random few jumps into the zombie 'spawn' and usually it pushes you out, but after a few attempts i managed to get myself literally stuck in the 'invisible wall' just randomly jerking back and forth 

http://i775.photobucket.com/albums/yy40/Xterm/Steam/zps_blackout0004.jpg

http://i775.photobucket.com/albums/yy40/Xterm/Steam/zps_blackout0005.jpg

(I assure you the photobucket folder is passworded and secure, only these direct links can view them)

Not that its a huge issue, and probably will never happen again, i thought id mention it. (may have even been due to my ping)

**Comment by Jonny-Steel** [comment]
First: Yes thx, I forgot to upload these custom textures (room 302) to the DevBuild. I will fix it.

Second: Interestng. This invisible wall is a func_humanclip. It should prevent humans to enter this area. Zombies can move freely. In this case it's obviously more the fault of the human player. If he trying again and again to enter this area. At the end you get stuck somehow. I think it's something we can ignore.

--- Bug report can be closed. ---
