### ISSUE TITLE
Limit the weapon carrying (Revolver) | Request

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#150]
Really.. one guy carrying 5 revolvers for himself? That's not fair and completely "idiot" for my opinion. We should limit it to 3 min; 2 in the max if possible.

![17500_screenshots_2013-09-19_00005](https://f.cloud.github.com/assets/4042019/1176016/ea3e3ace-2163-11e3-90dd-9b37318166d2.jpg)

**Comment by KamepeLaeske** [comment]
I second this. The magnum should use two inventory slots like the rifles, in my opinion.
