### ISSUE TITLE
Infection showing on all models of same type

### ISSUE THREAD

**Issue by bgwartney** [ZPSNMRiHIssues/zpsissues#153]
When a survivor gets infected, all of the survivors with the same model appear to be infected as well (turn green). However in the scoreboard, only the survivor that was actually infected shows up as green.

So if a Pedro becomes infected, all other survivor Pedro models will appear to be green and infected.

Reproduce:
Get two survivors with the same model, infect one.

**Comment by SammyROCK** [comment]
Should be fixed.
