### ISSUE TITLE
sv_testmode 1 does not force players back into lobby when activated

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#154]
If you decide to join in the map first (when no one else is in game), and then decide to activate sv_testmode, you won't get forced back into the lobby. However, players who then join in late can still spawn in normally as intended.

---

Steps to Reproduce
1) Get 3 people
2) Have one person spawn in the map without anyone else joining in
3) Type sv_testmode 1 in console and hit enter

**Comment by SammyROCK** [comment]
Fixed, sv_testmode should always change round into testmode state.
