### ISSUE TITLE
Zombie's health displayed as precentages

### ISSUE THREAD

**Issue by kettlekitten** [ZPSNMRiHIssues/zpsissues#162]
When you are either spectating a zombie, or are a fellow zombie and look at another zombie’s health, it displays it as a percent. Zombies however, unlike humans, have health that go up to 200% and 250%. I'm sorry if you guys already realized this and I'm just being redundant. 
![precents](https://f.cloud.github.com/assets/5685388/1328598/fdaed1ae-3504-11e3-9597-797b00c321ab.png)

**Comment by xerox8521** [comment]
I dont see whats the problem with it each percent stands for 1hp so 250% = 250HP

**Comment by Jonny-Steel** [comment]
Yes, kettlekitten is right. What's missing here is the reference to "its 250% of what?!". We know at the back of one's mind, that it is based on the human's health points. But not everyone does that. Because of that, it looks a little weird.

**Comment by xerox8521** [comment]
Should be easy to figure out for what it stands for if you know that carrier got 250hp or a zombie got 200hp it can only be the hp displaying as percentage. Also the game needs an inbuild tutorial which you have to play on first run of the game. Alot people i see do not even know how to do basic things like crouch jump and stuff like that.

**Comment by Wazanator** [comment]
Should say HP instead of percent, will check our dev build and see if this is still happening.
