### ISSUE TITLE
zpo_harvest | Request "player_clip"

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#167]
Found 1 (and maybe would be more) place that player can climb to a window, but zombies can't reach him.
![h1](https://f.cloud.github.com/assets/4042019/1647367/9a021564-593d-11e3-97ff-f5e659ce98e6.jpg)
![h2](https://f.cloud.github.com/assets/4042019/1647368/9a2c5310-593d-11e3-99ac-62bce1afeb74.jpg)

Need a PT day to test harvest, search for 'unfair' places.

**Comment by Wazanator** [comment]
I'll get on it

**Comment by Tabajara77** [comment]
Fixed
