### ISSUE TITLE
[Linux Server] List of 'to-do' for running a Linux Server in ZP:S + Bugs/Issues found in-game.

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#169]
Hi,
Currently, I'm running a dedicated server in Linux and somethings wasn't working correctly. So, I needed to 'rename' some folders to make ZP:S run, at least, normal for a good gameplay.
Here goes the list:
- ZPS server won't run if you don't rename the file "GameInfo.txt" to > "gameinfo.txt".
  Then the server can start up normally.
- Linux server might not start if the steam_appid.txt doesn't contain 17500 (Tested on debian and centos 6) (Thanks to Xerox)
- C4/IED doesn't work if you don't 'rename' the folder "v_IED" to > "v_ied".
  The folder is located in: models/weapons.
- Survivors walks with weird animation - with their arms up and legs frozen (T-pose) - if you don't rename the folder "Humans" to > "humans"
  ![2014-01-21_00001](https://f.cloud.github.com/assets/4042019/2021433/1a06327e-883f-11e3-8ec1-1aeebab32be6.jpg)
  The folder is located in the 'models' folder.
- Crowbar melee just flying in one spot but you still can grab it and kill a zombie.
  To fix it, rename the folder, located in hl2 folder, "Weapons" to > "weapons".
- The 'Voice Command' to ask for "ammo" doesn't work correctly in Linux servers, just in Windows servers. I mean, if you ask for ammo using the Voice Command, in the chat will just appear "(VOICE) Player : "ammo." "".
  I didn't find a fix for this one.
- Item crates boxes, from HL2 models, don't break if you don't rename the folder, located in "hl2" folder, "Items" to > "items".
- Probably 'cubemaps' issue (reflections) in-game. Just rename the folder "Env" to > "env".
  ![2014-01-27_00002](https://f.cloud.github.com/assets/4042019/2021423/0cac2200-883f-11e3-9fad-629f0cd8c75a.jpg)
  ![2014-01-28_00004](https://f.cloud.github.com/assets/4042019/2021425/11498726-883f-11e3-816b-babdab52a9bd.jpg)
  The folder is located in the 'models' folder.
- Lags spikes happens in middle of nowhere in-game. Server starts giving players bad pings ( closer to 999 ). It's like an attack of DDos, but it's not. I had it 3 times in one week. Got another server that's running a linux server too and everybody got bad ping.
  Currently, i only saw this happing in two servers ( They have Metamod and SourceMod running - 1.5.2 version )
- Server crash if a map request 'gibs' from a model. So fixed, changing the folder name,located in "hl2" folder "Gibs" to > "gibs".
- Some HL2 models are "not collide" correctly in-game (for example: crane model) - be sure the folder called "hl2" not is normal, not like "HL2". Folder is located at "zps/hl2" 

I'll keep this issue updated if i found more bugs/issues around. Last time updated : 05/17/2015

**Comment by Tabajara77** [comment]
Updated one more fix .

**Comment by JoelTroch** [comment]
My server didn't have that issue with the lags spikes happening in middle of nowhere in-game, so I guess this happens with an old Metamod Source and/or SourceMod versions (I'm running latest snapshots) or it could be the server itself.

However, the crash with ZPA maps is still there, I'm also looking on my side on what could be the cause.

**Comment by dedimark** [comment]
Thanks

**Comment by xerox8521** [comment]
Linux server might not start if the steam_appid.txt doesn't contain 17500 (Tested on debian and centos 6)

**Comment by Tabajara77** [comment]
Added to the list.
Updated list fixing up some grammar errors.
