### ISSUE TITLE
[REQUEST] Build in spawnkill protection

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#171]
Hi, im requesting an build in spawnkill protection where you cannot get any damage for like X seconds (changeable via convar) after spawn. This should exclude the infection turn function so if you turn = no spawnkill protection. Because especially on Maps like Church Armory and other camping maps you can get spawnkilled very fast without having the option to move (mainly zombies)

**Comment by GunF0x** [comment]
Why?

**Comment by Wazanator** [comment]
There are server plugins available that provide such features.
