### ISSUE TITLE
[Request] Remove these commands from the game.

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#173]
Commands to be removed from the game:
- sv_infinite_aux_power
- sv_hl2mp_item_respawn_time

**Comment by xerox8521** [comment]
Why remove sv_h2lmp_item_respawn_time ? ZPS uses them to respawn picked up items such as ammo and grenades

**Comment by Tabajara77** [comment]
Request from Dr.Vodker, saying that these commands are begin abused by some players/admins to get more ammo.

**Comment by jonnyboy0719** [comment]
These commands have now been removed, and no longer can be used.
