### ISSUE TITLE
Unable to see dedicated server in the server browser

### ISSUE THREAD

**Issue by tslocum** [ZPSNMRiHIssues/zpsissues#178]
Hello, I've just installed the ZP:S dedicated server, and configured it, using SteamCMD.  Once I got it up and running, I was able to connect to it (and play) by adding it to my favorites via its DNS name, or using the console "connect" command, however it is not visible in the public server list.  I've pasted my server.cfg here: https://gist.github.com/tslocum/78517c74b8af74e8c8c6

This is a Linux server, running MetaMod: Source as well as SourceMod, both of which appear to be functioning normally.  I don't have any firewall rules, and am able to run other Source servers on the same box without this issue.  If it helps, the server is located at zps.1chan.us:28015

**Comment by Will-Tango** [comment]
I'm going to take a wild stab in the dark, I think you just need to set your server region "sv_region" in your server.cfg it is commented out, give that a try. If I'm wrong I'm sure an expert will correct me.
Hope this helps

**Comment by tslocum** [comment]
Thank you for the suggestion.  This did not have any effect, sadly.  I did find the following, though: http://zombiepanic.wikia.com/wiki/Changelog

In the changelog, 2.4.1 states "Fixed servers not showing on server list.".  I noticed in the server browser (in Favorites/History) that my server is actually running 2.4, the previous version, yet I've just installed a fresh copy.  Perhaps this is the source of the issue?  I've used these two commands to install the server:

`app_update 244310`
`app_update 17505`

I had originally found these commands in the following guide: http://www.zombiegaming.org/zps-server-setup

So it seems that the version of the game in the SteamCMD repository is outdated?  Admins, could you please comment/fix?

**Comment by tslocum** [comment]
Doesn't seem like there's any interest in fixing this.
