### ISSUE TITLE
[Request] Reduce max body armor 100 to 50 with some gameplay changes

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#179]
The current stage of some ZPS players are that they always get two body armors only for them and leave other players without one body armor. 
Maybe if we change the max value to equip the body armor to only "50" and improve the resistance, we might make a better gameplay for our players - balancing both teams of course: zombies and survivors.

In a realistic way, "we don't equip two body armors in real life at all". 
The changes would be: "you can now only equip one body armor for you but the resistance would be improved to hold up the zombie attacks a little bit more (not the same feeling wearing two body armors "100", but would be 50% of it).

**Comment by jonnyboy0719** [comment]
this won't change due the hitboxes & hitreg has been fixed, its now easier for zombies to kill humans
