### ISSUE TITLE
Ghost boards!

### ISSUE THREAD

**Issue by Wazanator** [ZPSNMRiHIssues/zpsissues#18]
What led up to this:
1. Previous round was about to put up a barricade when we won due to the timer
2. Killed myself next round to test something out
3. walked into there as a zombie and the ghost cade icon was there

No one else could see it only me.

http://steamcommunity.com/id/wazanator/screenshot/578985893042095767

**Comment by Jonny-Steel** [comment]
Hmmm weird. I believe it's not map related. ^^ ... For myself, I see something like that the first time.
