### ISSUE TITLE
[Request] Make unable to 'panic' in the beginning of a new round

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#182]
Do I really need to explain this request? Well, we're still in 2015 and people think 'panicking in the beginning  of the round is an "advantage", but in the end it's not! Newest players think doing that is a good thing, but we should put an end on this, make panic button unable to use in the first 10 seconds in the starting of the round.
Make them use and hold their ammo and pistol with them.

Example of a message to pop up in the chat box: "There's no reason to panic right now. The round has just started."

**Comment by xerox8521** [comment]
I don't know if this still works but will2tango did a plugin some time ago.
If it works it can be used until a better solution is implemented.
https://forums.alliedmods.net/showthread.php?p=1268751

**Comment by KamepeLaeske** [comment]
I wouldn't mind this change :)

**Comment by jonnyboy0719** [comment]
I did use his plugin ages ago, because panic was abused alot ( still is ). And I will make sure to implement this later today with a new convar, so you can change on the flow (min sec will be 10, and max maybe 25). Since I know there is a plugin where you can set specific convars for certain maps, so It will be handy for that, plus some maps you spawn pretty close to the zombies (Tanker for example).

But yeah, expect this to be implemented :)

**Comment by Will-Tango** [comment]
Thanks Johnny, This will be a very welcomed addition!
I'm glad my plugin helped in the meantime, but you just cant beat having it built into the game :)
Looking forward to future updates!

**Comment by GunF0x** [comment]
I think this needed to be in years ago, kudos for finally paying attention
to some of the glaring issues! Zombie life breathes again into this old
project. Thanks for the work.

**Comment by xerox8521** [comment]
There shouldnt be a hardcoded lower limit.

**Comment by Will-Tango** [comment]
I agree with xerox, I think just a default value of maybe 3 or 5 seconds would be ideal

**Comment by jonnyboy0719** [comment]
min limit has been set to 0, and default will be 0. So servers has to set the value (max is 25 seconds)

**Comment by GunF0x** [comment]
So why are players allowed to panic at round start at all? It's a shitty
mechanic, they are not running from anything yet. Shitty players just use
it to race to the best guns and then hoard.

**Comment by GunF0x** [comment]
The levels that use the panic at start can be easily modified to automate
the panic so every player starts off on the same footing, ala bloodbath,
tanker, hc maps etc, so why not make the default for the cvar 2-3 seconds
so players don't immediately drop all equipment and go into selfish race to
gun mode (which immediately drops their chances of winning well below 10%).
Alternatively if everyone loves panic at start of round, why not just give
everyone a speed boost so new players have a chance at learning the levels
and locations of guns without some selfish player panicking and stealing
them all with no intention of working with his team

**Comment by Will-Tango** [comment]
I agree, even a short default of 1-3 seconds would help discourage players from dropping valuable ammo at the spawn point. 

I would recommend either preventing players from dropping ammo and guns as well as blocking panic or adding that as an option, even if players cant panic they can still drop everything for a tiny speed boost in the hopes of grab a bigger gun. But that maybe overkill.
