### ISSUE TITLE
Developer console error related to HUD elements

### ISSUE THREAD

**Issue by BreakinBenny** [ZPSNMRiHIssues/zpsissues#185]
In the developer console, these errors pop up:

```
Hud element 'CZPHudIndicators' doesn't have an entry 'HudIndicators' in scripts/HudLayout.res
Hud element 'CHudImage' doesn't have an entry 'HudImage' in scripts/HudLayout.res
```

**Comment by jonnyboy0719** [comment]
Missing / unneeded HUD elements has been removed

**Comment by BreakinBenny** [comment]
Does this mean you _won't_ fix the problem?

**Comment by jonnyboy0719** [comment]
it basically means it has been fixed, It was trying to show old elements that isn't in-game anymore

**Comment by BreakinBenny** [comment]
Elements such as...?

**Comment by jonnyboy0719** [comment]
as the ones that were shown above. If they got removed from the hudlayout.res, it means they got obsolete/no longer needed because something else replaced it, but why they were still in the code, is beyond me. Other than that, its nothing that can cause the game to break, they just won't show on your HUD.

**Comment by BreakinBenny** [comment]
I just want to share some more developer console errors: `Error! Flag "$nocull" is multiply defined in material "models/zp_props/wood"!
Error! Flag "$nocull" is multiply defined in material "models/zp_props/branches"!
SOLID_VPHYSICS static prop with no vphysics model! (models/props_lab/corkboard002.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/bramble001a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/bramble001a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/shrub_01a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/shrub_01a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/shrub_01a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/cattails.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/cattails.mdl)
`
`Unknown command "sk_stalker_health"
Unknown command "sk_stalker_melee_dmg"
Unknown command "sk_zombie_health"
Unknown command "sk_plr_dmg_crowbar"
Unknown command "sk_npc_dmg_crowbar"
Unknown command "sk_plr_dmg_stunstick"
Unknown command "sk_npc_dmg_stunstick"
`
`Bad sequence (4095 out of 12 max) in GetSequenceLinearMotion() for model 'zombies\zombie1\zombie1.mdl'!`
`--- Missing Vgui material vgui/..\vgui\maps\menu_thumb_cp_badlands`

**Comment by BreakinBenny** [comment]
Now, on zps_asylum. Bear in mind that I'm rather nitpicky, but I hope that's OK!

`
***need to set $abovewater for material maps/zps_asylum/dev/dev_water2_cheap_320_-88_-17
***need to set $abovewater for material maps/zps_asylum/dev/dev_water2_cheap_2804_2644_-24
***need to set $abovewater for material maps/zps_asylum/dev/dev_water2_cheap_-348_564_64
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/ivy_01.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/ivy_01.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_lab/frame001a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/ivy_01.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/ivy_01.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_lab/generatorhose.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_lab/generatorhose.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/ivy_01.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/ivy_01.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/bramble001a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/bramble001a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/bramble001a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/bramble001a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/shrub_01a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/shrub_01a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/shrub_01a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/bramble001a.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/tree_deciduous_card_01_skybox.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/tree_deciduous_card_01_skybox.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/tree_deciduous_card_01_skybox.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_foliage/tree_deciduous_card_01_skybox.mdl)
`
`
ERROR!: Can't create physics object for models/props_c17/pushbroom.mdl
ERROR!: Can't create physics object for models/props_c17/pushbroom.mdl
`
This means the brooms were to be physics props, right? Too bad!... Now, zps_blackout:
`
Error! Variable "$envmaptint" is multiply defined in material "models/zp_props/cinema/cinema_sign_1l_diff"!
Error! Variable "$envmaptint" is multiply defined in material "models/zp_props/cinema/cinema_sign_1r_diff"!
Error! Variable "$envmaptint" is multiply defined in material "models/zp_props/cinema/cinema_sign_2l_diff"!
Error! Variable "$envmaptint" is multiply defined in material "models/zp_props/cinema/cinema_sign_2r_diff"!
Error! Variable "$envmaptint" is multiply defined in material "models/zp_props/cinema/cinema_sign_3l_diff"!
Error! Variable "$envmaptint" is multiply defined in material "models/zp_props/cinema/cinema_sign_3ur_diff"!
Error! Variable "$envmaptint" is multiply defined in material "models/zp_props/cinema/cinema_sign_23r_diff"!
Error! Flag "$selfillum" is multiply defined in material "models/clubzombo/neon_blue"!
`

**Comment by BreakinBenny** [comment]
I could go into all the official maps for console errors, but to be honest that'd leave me with only VMT files to fix...

**Comment by Tabajara77** [comment]
Thanks, but we'll check on our own for now. Since it's a new Source engine, we'll be working on the maps on the way. Thanks for letting us known about those errors on the "developer 1" console.

**Comment by jonnyboy0719** [comment]
most of these errors can be ignored, these are the default Source issues which will never go away, and we don't have engine access so don't expect these to be fixed. (If you load up any MP or SP mod, these errors will popup no matter how hard you try)

**Comment by BreakinBenny** [comment]
In that case I could supply fixed VMT files, while you guys take care of the map-related ones. the SOLID_VPHYSICS problem can usually be fixed by finding the prop_static and making it **Not Solid**.

**Comment by jonnyboy0719** [comment]
yeah, It's basically telling the mapper '_hey, you are trying to set this model with the flag "Is Solid", but there is no .phy file for this model_'
