### ISSUE TITLE
[Request] Option to download only custom maps; not other files

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#187]
Add one more option for downloading custom content from a Server:
"Do not download custom models, textures and sounds; just maps."

In Options>Multiplayer.

**Comment by jonnyboy0719** [comment]
If a map has a res file, then It wouldn't really download anything, and it would just have errors everywhere. Which forces people to pak all their files into their BSP which will only lead the maps having a massive size, which will take longer to download.
