### ISSUE TITLE
[ZP!S SDK 2007] Autoinfection does not cancel out infection if a new whitey is found

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#189]
Usually, when someone leaves as whitey when there are few zombies, the autoinfection will randomly infect a player. However, most of the time, the Autoinfection will not cancel out the infection if a new player joins the zombie team, taking over the whitey. 

This allows players playing whitey to get a free infection on the survivors by rejoining the game.

**Comment by jonnyboy0719** [comment]
Auto infection now cancels out if a zombie player (1 or more) has been found.
