### ISSUE TITLE
zpo_silentskies multiple small bugs

### ISSUE THREAD

**Issue by xterminator1986** [ZPSNMRiHIssues/zpsissues#19]
Can't seem
![zpo_silent_skies0008](https://f.cloud.github.com/assets/4086342/349373/cfe5efd0-9fbf-11e2-903b-4344ba0696e6.jpg) to climb ontop of these crates, im not sure if you're supposed to be able to or not, however.

![zpo_silent_skies0009](https://f.cloud.github.com/assets/4086342/349376/ef8b9074-9fbf-11e2-8621-f31273d25cc5.jpg)

![zpo_silent_skies0010](https://f.cloud.github.com/assets/4086342/349378/1aad6066-9fc0-11e2-826d-03a0d14ea0a2.jpg)

![zpo_silent_skies0011](https://f.cloud.github.com/assets/4086342/349379/229ea1f4-9fc0-11e2-80b9-89a82c960892.jpg)

As you can see in the above images, some of the metal between the glass to the skybox seems to be 'sliced off' when you move around at different angles.

**Comment by SiggyWiggyWoo** [comment]
I'll remove the player clip above the box, I'll fix those metal bars up too.
