### ISSUE TITLE
[ZP!S SDK 2007] Team Win dragging on ZPO 

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#190]
Most of the time, ZPO maps will not trigger a team win in time. 
- If survivors reach the extraction point, it can be up to 2 minutes before the game detects the win. 
- If all survivors are killed, it can be up to 2 minutes before the game detecs a win.

**Comment by Tabajara77** [comment]
It's the "infected survivor" issue. #184

**Comment by KamepeLaeske** [comment]
It may be related but I believe this a different issue. It also happens even if no survivors are infected. From experience, it seems to be triggered if a survivor is killed or infected in or near the extraction zone.

**Comment by Tabajara77** [comment]
Also #48
