### ISSUE TITLE
[ZP!S SDK 2007] Switching weapons cancels out gunshots 

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#194]
If a player switches their weapon as soon as they fire a shot, the sound of the gunshot will be cancelled.

**Comment by jonnyboy0719** [comment]
This happens if the weapons doesn't have a "cooldown" for when you shoot. It will basically tell the game that you need to wait 0.5 seconds or up to 1 second, before you can switch and/or drop weapons.

**Comment by jonnyboy0719** [comment]
Fixed on the SDK 2013 version
