### ISSUE TITLE
[SUGGESTION] [ZP!S SDK 2013] Expand the Roar Ability 

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#196]
Give whitey the ability to make survivros appear through walls for other zombies if he has direct eye sight at them/close to them. Whitey should also shine in a different color when using roar to signal the other zombies.

**Comment by NjMuffin** [comment]
Nice feature, I really would like to see this in the new build.
Just please allow the players to toggle this option on or off because for low-end computer users this might actually cause some framerate issues.

**Comment by xerox8521** [comment]
Maybe it would be possible to make it flashing ? Or even change between static glow (glow that always shows if roar is on) and flashing flow which goes on and off continually.

**Comment by jonnyboy0719** [comment]
That will require more networking, due you are killing off the old one, and turning on a new one with new values. So that won't happen.
