### ISSUE TITLE
[SUGGESTION] [ZP!S SDK 2013] Rework barricades 

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#197]
As of right now, they take way too much damage from physics, usually breaking instantly upon contact with an object. 

The damage that the boards recieve from zombies is fine, in my opinion.

**Comment by haxtozous** [comment]
Maybe while reworking barricade physic damage, you could also change the sound it makes when hitting a survivor placed barricade? To a new player experienced with source but not with ZPS, barricade boards don't really sound breakable.

**Comment by DoofusCockslap** [comment]
Gotta note that it‘s better to fix the fullbright board gibs as well.
