### ISSUE TITLE
[ZP!S SDK 2007] Players can spam voice commands by jumping

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#198]
Jumping seems to reset the cool-down on voice commands, making players able to spam them by jumping repeatedly. This can be done so an even greater extend if players crouch below a ledge or similiar with a small space for jumping.

**Comment by jonnyboy0719** [comment]
Fixed on the SDK 2013 version, which has been given a proper cooldown system
