### ISSUE TITLE
[SUGGESTION] Restore the bios of playable survivors and Carrier

### ISSUE THREAD

**Issue by BreakinBenny** [ZPSNMRiHIssues/zpsissues#202]
I remember back around version 1.4, there were bios for Eugene and Marcus... including the Carrier zombie. Why were they removed and why do we only have Tatsur0's template? I hope you bring them back because, I'd like to know.

**Comment by Tabajara77** [comment]
That must be related to a SQL/URL website that saved those information about all survivors and the Carrier. I'll look into.
