### ISSUE TITLE
zpo_biotec keycard hint is wrong.

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#204]
Since the update of biotec there is now a info_beacon attached to the keycard when you are close. However sometimes it shows at for example the big hall (the beacon) but the actual keycard model and another beacon is in for example the red rooms. Not sure if this can be fixed by the mapper or this is a code issue.

**Comment by jonnyboy0719** [comment]
It is a code issue on the old SDK 2007 version. It never calls "TurnOff" properly. It will be fixed up on the SDK 2013 version.
