### ISSUE TITLE
zps_nightmare problems

### ISSUE THREAD

**Issue by BreakinBenny** [ZPSNMRiHIssues/zpsissues#206]
On zps_nightmare:

```
Precache of materials/sprites/orangecore1 ambigious (no extension specified)
Empty ambient_generic (ambient_generic) at 403.00, -776.78, 386.32
```

On Police Station:
`Failed to load sound "wheel\ambient\phone\payphone-01.mp3", file probably missing from disk/repository`

**Comment by Tabajara77** [comment]
Just minor stuff on developer 1 console. Nothing major, i'll take a look.
