### ISSUE TITLE
[SDK 2013] CleanUpMap() crashes the game

### ISSUE THREAD

**Issue by jonnyboy0719** [ZPSNMRiHIssues/zpsissues#207]
When the round ends, the CleanUpMap() can crash down the game, this must be looked into.

Possible entities that can cause the crash:
- player
- weapon_*
- item_*
- env_*

**Comment by jonnyboy0719** [comment]
found possible entity that can cause the crash, will be looked into..

**Comment by GunF0x** [comment]
So if one is going to troll by removing people from the PT group, might one
wanna come out and be a man about it?

**Comment by Tabajara77** [comment]
GunFox add me on Steam http://steamcommunity.com/id/Tabajara77
