### ISSUE TITLE
[SDK 2007] Zombies can push up the Lunge on spectators (Lobby).

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#209]
There is an issue where zombies can push up their lunge and even reach beserk by attacking players which are in lobby. Now this is usually not a problem if mappers add a proper lobby but some maps dont have it which cause players to spawn somewhere in the map.

**Comment by jonnyboy0719** [comment]
This won't be a problem anymore on the SDK 2013 verison. But I do think the mappers need to make a proper lobby, or a lobby far away from the gameplay section etc
