### ISSUE TITLE
Zpo_Blackout Various Texture Bugs

### ISSUE THREAD

**Issue by DiGSurvivor** [ZPSNMRiHIssues/zpsissues#21]
Location 1:
Outside on the side of the large apartments there is a window that you cannot go through, but can glitch into.

Pictures 1:
https://www.dropbox.com/s/9pi1epjzjdokhai/2013-04-07_00004.jpg

https://www.dropbox.com/s/rjpuzsmitktetlt/2013-04-07_00002.jpg

https://www.dropbox.com/s/ltapgo31f1dw3ex/2013-04-07_00003.jpg

Location 2: Outside by the oil truck in the back of the map there are barrels with missing textures on one side.

Pictures 2:
https://www.dropbox.com/s/ex3kk2fwjsi36ep/2013-04-07_00007.jpg

https://www.dropbox.com/s/1jupwrdfwsla9at/2013-04-07_00009.jpg

Location 3: Zombie spawn in room 302

Pictures 3:
https://www.dropbox.com/s/llp3szuxbocvvz5/2013-04-07_00006.jpg

https://www.dropbox.com/s/ejrgqe2am8920h9/2013-04-07_00005.jpg

**Comment by Jonny-Steel** [comment]
Location 1: Yes, ... that's a zombie short cut into the zombie spawn area in the basement. Like a coal chute. Only zombies can use it. The effect you see is a side effect. I will put a func_human_clip there to fix it. Thx.

Location 2: Yes, I know that. This static_prop has no texture at the bottom. Was hoping nobody will notice. I will see what I can do.

Location 3: Yes thx, I forgot to upload these custom textures (room 302) to the DevBuild. I will fix it.

--- Bug report can be closed. ---

**Comment by DiGSurvivor** [comment]
NP, and nice work on the map.
