### ISSUE TITLE
[SDK 2007] Lobby music doesn't stop on map change.

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#210]
So apparently some mappers think they're funny in adding music to the lobby which is already annoying but actually worse is that it doesn't stop on map change. You have to close the game completly and restart it to get rid of the music. For an example take a look on zpo_ancient.

**Comment by jonnyboy0719** [comment]
it looks like SDK 2007 doesn't stop the event "ambient_play" properly. This will be fixed on the SDK 2013 version
