### ISSUE TITLE
[Request] Achievement names 

### ISSUE THREAD

**Issue by NjMuffin** [ZPSNMRiHIssues/zpsissues#211]
Seeing this game is going to get achievements is really cool but I think they shouldn't just have dull names which sound the same as their own description. 'Kill x zombies with magnum' is alright but it would be better if it had a name called 'Hawk Eye'  or for Aquatica there could be an achievement called 'Hide 'n Seek' - Don't let the humans get your keycard for 60 seconds. 
Also making small references to some popular zombie movies and games is also a neat thing to do. 

And for our campfire friends we could just give them an achievement called 'Sentry' - Don't move for 5 minutes while killing at least 10 zombies.

**Comment by Zero1891** [comment]
Italian plumber or Jumpman and you need to jump on 3 zombies in a row
