### ISSUE TITLE
[SDK 2007] Pistols don't use unload animation

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#215]
It was like this for decades and still not fixed.
Currently all the pistols (Both Glocks, USP and PPK) use "reload_empty" animation instead of "unload" one although they have "unload" animation in their viewmodels.
Feel free to close this one if it's fixed in dev build already.

**Comment by jonnyboy0719** [comment]
This has been fixed on SDK 2013
