### ISSUE TITLE
[Suggestion/Request] Adding a playercount trigger-volume entity to the code

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#217]
If you're familiar with the mod Zombie Master you may know that there are similiar entities right there.

"trigger_entitycount" and "trigger_playercount". The second trigger detects the specific percentage of players out of current number of human players alive needed to send an output.
For example we have 10 survivors alive and the trigger requires only 30% of the team to be inside to activate it. That means only 3 survivors will be enough to activate it. This sort of triggers can make creating some objectives a way easier for mappers.

**Comment by jonnyboy0719** [comment]
I think this kind of trigger would be cool to have, more options for the mappers, and can probably make some neat stuff for the objective maps. I will look into this, since I really like this idea, but might flesh it out even further

**Comment by JoelTroch** [comment]
Isn't this already doable with the standard HL2 entities ?

I mean "trigger_multiple" -> OnEnter/OnExit -> math_counter ?

**Comment by jonnyboy0719** [comment]
Its better to make a new entity that can do this in 1 go, than making a unnecessary complex system to do so. We can basically take down the need of having 3-4 entities to just having 1, we will basically save on our entdata.

**Comment by JoelTroch** [comment]
Sure ^^

**Comment by jonnyboy0719** [comment]
This trigger has now been added on the SDK 2013 version, will be easier for level designers to make certain objectives or other neat stuff.
