### ISSUE TITLE
[SDK 2013] [SUGGESTION] Support for the CSS Menu Style

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#218]
So know from HL2MP (which is the base) it has the valve menus which tbh aren't good. So i would like to put a reminder to change the menu style to css one. 
For those unfamiliar with the valve menu:

http://i31.tinypic.com/24ybf6f.jpg

CSS Menu style:

http://i25.tinypic.com/2822jag.jpg

**Comment by jonnyboy0719** [comment]
SDK 2013 build already has the radio schemes inside SourceScheme.res, so it will automatically read the radio buttons, just like ZPS did in SDK 2007.
