### ISSUE TITLE
[REQUEST] [ZP!S SDK 2013] Add option to remove "Blood Splatter" when being hurt as zombie

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#219]
This would make maps that include damage being done to zombies through entities and triggers a lot less tedious to play. This is a issue we've run into with pithole and it would be awesome if the blood could be turned off while still doing damage. Survivors appear to have this feature, with blood appearing when they are being attacked but they can also take damage without the blood appearing.

**Comment by jonnyboy0719** [comment]
I could look into this, and make sure it only applies to player dmg

**Comment by KamepeLaeske** [comment]
Would be splendid :)

**Comment by DoofusCockslap** [comment]
btw, surivors get this blood splatter effect when wearing armor. (there is a good example of what I mean on zpo_snowbound).

**Comment by jonnyboy0719** [comment]
yeah, the code isn't checking for "player incoming damage", it will display if you loose any HP %
