### ISSUE TITLE
Silent Skies - VIP Lounge, Table Problem

### ISSUE THREAD

**Issue by SgtMartin** [ZPSNMRiHIssues/zpsissues#22]
![2013-04-07_00002](https://f.cloud.github.com/assets/4086686/349419/56c4f9b8-9fc2-11e2-8fac-42786f0c8605.jpg)

The tables in the VIP lounge all have glasses on them that trip up players. You can neither break, nor move them, which makes it a slight pain when you're table hopping, looking for the key card. The same glasses model is used in zps_blackout, with the difference being that blackout's models allow you to pass right through them.

**Comment by xterminator1986** [comment]
![zps_blackout0007](https://f.cloud.github.com/assets/4086342/349439/e5ecb044-9fc3-11e2-800d-57eb7f06ef4e.jpg)

Here, i actually saved a picture of the glasses from earlier on, mainly to make a joke about the bartender being so lazy and only pouring one drink, but here you can see, you CAN walk through them.

**Comment by Wazanator** [comment]
Thats because in blackout Jonny made them nonsolid

**Comment by SgtMartin** [comment]
Perhaps the solid state of the glasses in silent skies was intended then. Sorry, if true! Just feels weird to have to maneuver around them. :(

**Comment by SiggyWiggyWoo** [comment]
Not intended, I'll make them nonsolid.
