### ISSUE TITLE
[Suggestion/Request] "trigger_infection" and manual infection output

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#220]
The concept for this trigger and output is simple. It's for objective maps and can be used to manually infect players by scripted conditions and events (for example to prevent camping or for traps on ZPO maps). I think it's obvious enough what this does on a paper. 
If it's not, then here is an explanation:

First of all speaking of manual infecting players as an additional feature there can be added an output for "!player" that will manually infect player by the server command or entity output instead of using the said trigger_infection (this output might come in handy as a debug feature in general).

As for trigger_infection, it can be activated only by survivors team. 
If you walk into this trigger you get infected with an infection chance setup by mapping 
(keyvalue in properties). Example: 1.0 is 100% 0.25 is 25% etc. 

The main thing is that you can setup trigger to work in two modes. The first mode works similiar to "trigger_once" where you get only one chance of getting infected by a single trigger interaction (trigger ent_removes/kills itself on activation, which can be used in very specific scenarios) and other mode that simply works like "trigger_multiple" where you can reactivate it multiple times (you also can set keyvalue how many times you can use trigger_infection, but only in trigger_multiple mode). 

In addition to that you can set the "Random Timed Infection" mode (by Yes/No in properties) where it might infect players not instantly (like in "trigger_once"), but if you stay long enough in this trigger (time in seconds that must be setup if "Random Timed Infection" is enabled, plus you should set the infected chance as well. "Timed Random Infection" works only in "trigger_multiple" mode.

That's it.

**Comment by xerox8521** [comment]
This would hurt to much the actual gameplay if mappers randomly place them everywhere and tbh not really useful or makes much sense. Thats not how infection works.

**Comment by DoofusCockslap** [comment]
Well, this depends on mappers themselves. There are lots of custom maps that are completely broken or unplayable because some mappers abuse some game mechanics to make their map "fun". 
Anything may hurt an actual gameplay if people use it wrong or abuse it too much.  If you're good with the tools you have in your hands you can do many good things.

**Comment by jonnyboy0719** [comment]
We will see if I will add this in or not, only time will tell.
