### ISSUE TITLE
[SDK 2007] General viewmodel "eject brass" bug

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#223]
Some weapons have a bug of producing a wrong number of shells on a single shot. 
For example if you make a single shot with an AK-47 (or other rifle/pistol) it will produce 3 shells instead of one. Also worth to mention that viewmodels of pistols don't have ejectbrass event compiled in.
Even if you recompile the viewmodel of a pistol with eject brass event added in, it will have this bug still.

**Comment by jonnyboy0719** [comment]
This has been fixed on SDK 2013, the reason why it happened is due valve didn't set a delay timer on **EjectBrass** which can be found here: https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/client/c_te_legacytempents.cpp#L1642

To fix this, this piece of code had to be added under _pModel_:

```
    if (m_flEjectBrassTimer > gpGlobals->curtime)
        return;

    // Since EjectBrass want to spam bullets, lets add a delay timer.
    m_flEjectBrassTimer = gpGlobals->curtime + .1;
```
