### ISSUE TITLE
[SDK 2013] [SUGGESTION] Glow support for mappers.

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#225]
I think that may be useful for mappers to add glow support to entities just like in l4d(2) where you can specify the type (flashing, constant glow) the range where it is shown and the rgb (alpha) values. So mappers could highlight entities.

**Comment by jonnyboy0719** [comment]
this isn't really needed due ZPS already have the icon marker, which can be applied on any item. And only item_delivery will have full color support for the item pickup due it was meant to have glow support. (Glow support will not work on brushes either, this method only works on Alien Swarm and / or l4d engine branches)
