### ISSUE TITLE
[SDK 2007 / Minor] Weapon reloading sounds not in sync

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#226]
Sometimes weapon sounds don't play in sync with the animations. Note that sometimes reloading sounds play fine, but sometimes they lag out of the reloading time. This is very easy to notice when you're on server with +100-150 ping for example. Happens only with the pistols, rifles and revolver. Shotguns don't have this issue due to different reloading sequences.

P.S. Just wondering if it's related to ZPS code itself and not to Source Engine overall.

**Comment by jonnyboy0719** [comment]
Its not related to ZPS only, this goes to every single Source engine game that uses the old play sound system used inside of the weapon script. This has been fixed in SDK 2013 however, due we have changed it to the more accurate Event system.

**Comment by DoofusCockslap** [comment]
Alright, thanks for checking this out.
