### ISSUE TITLE
[SDK 2007 / 2013 Request] Removing crouching speed penalty for ladders/water

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#227]
I remember back in the day before 2.4 release when you were crouching you still were able to swim and climb the ladders with the same speed as if you were standing. 
The crouching is very bugged in general right now in the current public build and it's very annoying
(not to mention the crouch jumping third-person animation, which looks awful)
Here are my thoughts on the speed penalty in the water (and on ladders):
If you try to swim under water (or climb the ladder) and press crouch button you will be extremely slow until in water case:
You touch the ground (you will stand back up then and gain a normal movement speed).

In case of ladders:
You will have to release the crouch button and wait a couple seconds until you get back your normal climbing speed.

**Comment by jonnyboy0719** [comment]
the crouch issue on water and ladder has been fixed on SDK 2013 version.
