### ISSUE TITLE
[Keretti] Table glitch and automatical round end in favor for survivors.

### ISSUE THREAD

**Issue by NjMuffin** [ZPSNMRiHIssues/zpsissues#228]
https://www.dropbox.com/s/o1i3n921n63ai2z/20161008022750_1.jpg?dl=0
For whatever reason the table moved so we namaged to flip it.

The other issue on this map which happened was that humans automatically won the round even tho they had to turn on the power switch located right next to the gas switch. Usually the round goes on until zombies kill all the survivors or humans managed to turn on this power switch to set the zombie spawn on fire. 

Note: I managed to turn on the gas switch but died so the power switch was the last objective left to do and no one was near it to press it when the humans won. This autowin for humans should not be happening especially when there are only 3 survivors left while 16 zombies are hunting them down.

Edit: This is not a perfect screenshot but on the right side you see it says that survivors have to turn on the power switch. I decided just to turn on the gas and after 10 sec the game let survivors autowin again.
https://www.dropbox.com/s/ga2chd9j21kfj59/20161008030703_1.jpg?dl=0

2nd edit: Please ignore the table issue, it was just because of the server itself. The objective issue still needs to be tested tho.

**Comment by DoofusCockslap** [comment]
I've seen this auto-win issue many times before. The final objective always was this buggy.

**Comment by Tabajara77** [comment]
Table is confirmed is server-side. The last obj might be fixed on 2013 but I'll make sure. Thanks for the report.
