### ISSUE TITLE
zpo_silent skies - waypoint disappearing & reappearing

### ISSUE THREAD

**Issue by RanmaZPS** [ZPSNMRiHIssues/zpsissues#23]
Gone,
http://steamcommunity.com/sharedfiles/filedetails/?id=137591314
And just a few steps...
http://steamcommunity.com/sharedfiles/filedetails/?id=137591334

**Comment by SiggyWiggyWoo** [comment]
Working as intended, it's an extra side objective. Can be done at anytime or at the end if no one knows about it.

**Comment by RanmaZPS** [comment]
It's not good for it to disappear, though. This happened when Martin and I were the last alive. We were doing the can objective and someone else was doing the other objective. When we did the can objective we were stoked and then out of nowhere that objective shows up. We didn't notice because we were so focused on the can objective. So when we thought we were done Martin has to go down and push dat shit around and I have to defend him. Wouldn't be a problem except the zombie kept spawning on us and we got overwhelmed.
