### ISSUE TITLE
[Suggestion] ZP:S 2013 - Revolver and MP5

### ISSUE THREAD

**Issue by Zero1891** [ZPSNMRiHIssues/zpsissues#232]
The dmg on the revolver should be reduced to 190 on headshots so to give regular zombies a chance.

The MP5 should be using Pistol ammo

**Comment by xerox8521** [comment]
It would feel less rewarding for players who actually have the skill to headshot zombies with the magnum. When i headshot a zombie with the magnum i want to get the reward in killing the zombie (except the carrier).
Agree on the MP5 one.

**Comment by Tabajara77** [comment]
We have adjust some weapons balance on that, but removing the revolver damage of 1 headshot kill would effect the gameplay too much. But we have some plans for revolver in 2013 build.

**Comment by DoofusCockslap** [comment]
Just had a thoughts about balancing revolver. 

I don‘t mind the current damage, but here are two ways how we can probably balance out the revolver.

1st example:
-Make a new reloading animation which will be longer and more detailed. Maybe something similiar to hl2. We take shells out, inserting a new shells (btw, revolver model has speedloader part, but doesn‘t use it in current anims), putting the cylinder in the place and spin it.
-Increase a recoil (somewhere around +25-35%).
-Decrease the fire rate (-45%).

2nd example:
-Leave the same reloading animation
-Nerf the damage (by 75-85% of its current dmg)
-Increase the fire rate (faster by 50%)
-Decreace the recoil a little, but not too much.
