### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by broli95** [ZPSNMRiHIssues/zpsissues#234]
It happens everytime I finish playing and quit the game from the main menu. I can do nothing to make it go away, the only thing I can do is to manually shut down my pc. I'm using the beta version.

**Comment by xerox8521** [comment]
Try to use the normal version. You should no longer need the beta version

**Comment by DoofusCockslap** [comment]
Killing hl2.exe process in task manager usually helps in this kind of situation instead of shutting down whole PC.

**Comment by broli95** [comment]
Maybe I was not clear, I have black screen and can do NOTHING while I have it. Of course I'd use the task manager if necessary however I can't.

**Comment by jonnyboy0719** [comment]
This usually happens on low end systems that run Source Engine. This cannot be fixed unless access to the engine itself.

**Comment by broli95** [comment]
Low end system? not my case sorry, my pc is good enough to run crysis 3 and other heavy games, THIS ONE is the only one that gives me this problem. I removed the beta application but it still happens, I get into the game then i exit: black screen, can't do anything. It's not my problem but the game's

**Comment by KamepeLaeske** [comment]
What OS are you using? 

What settings are you running the game? 

What are the temperatures of your GPU and CPU while playing?

**Comment by broli95** [comment]
It seems that I was able to solve the problem by running it in windowed mode. In fullscreen mode i get this problem.

**Comment by KamepeLaeske** [comment]
That's great! Are you running Windows 10? The 2007 build is really unstable due to its broken code, rendering almost unplayable on Windows 10. This will be fixed in 3.0. 

If you are running Windows 10 try and set '-dxlevel 90' in your launch settings and run the game in compatibility mode I see if that fixes the issue.

**Comment by broli95** [comment]
Yes I'm on Windows 10 anniversary edition, do i have to set those launch settings for ZPS or SDK 2007?

**Comment by jonnyboy0719** [comment]
Run the following commands for ZPS 2007:
**-sw  -noborder -dxlevel 80 -low**

It will make the game playable, but it will still crash due the 2007 version is very unstable.

**Comment by broli95** [comment]
The game runs fine, the problem is when i exit. So no need to.
