### ISSUE TITLE
[Harvest] FPS Drop Issue 

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#235]
Inside/Front the house - specially with HDR FPS drops heavily.
Checked without RAD works fine tho.

Selfnote to check it on 2013 and optimize it somehow.

**Comment by DoofusCockslap** [comment]
After playing a slightly updated "holiday" themed Harvest last night, now I get what fps drops you mean here.

**Comment by KamepeLaeske** [comment]
The new lightning stresses the 2007 engine and it hurts the optimization. On 2013, it works fine, and we won't be doing anymore work on 2007
