### ISSUE TITLE
zpo_anoxia door jam( general door jam)

### ISSUE THREAD

**Issue by darbdude** [ZPSNMRiHIssues/zpsissues#237]
![20161028093128_1](https://cloud.githubusercontent.com/assets/4066412/19814463/1e722a9a-9cf3-11e6-83a3-744bb662e357.jpg)
![20161028093058_1](https://cloud.githubusercontent.com/assets/4066412/19814465/1e867018-9cf3-11e6-8fc7-8cb7c9b62a01.jpg)

**Comment by jonnyboy0719** [comment]
anoxia is not a stock map. ZPS Github is not a place to report community maps. You have to contact the creator of the map to get it fixed.
