### ISSUE TITLE
[MINOR] Zombie team name change

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#238]
Currently in the old 07 SDK zombies are considered as "Undead" which is not wrong but i would prefer to have it Zombies. Also fits more the mod name. "Undead Panic Source" sounds weird.

**Comment by DoofusCockslap** [comment]
I personally prefer “Undead“ more, because it sounds more unique than just “Zombies“. The word “Zombies“ is used a way too often in this game, so it‘s better to have some variety to how we can call zombie team. Also why can‘t we rename “Carrier“ to “Whitey“ for the same reason then?

**Comment by xerox8521** [comment]
Because hes actual "carring" the infection and spreading it.

**Comment by KamepeLaeske** [comment]
By that logic, calling zombies undead is completly legitimate as they are undead. I prefer undead and carrier over zombies and whitey as well. The wording would otherwise only seem unfitting and unimmersive - of course on a very small scale given its role in the grand scheme of things.

**Comment by DoofusCockslap** [comment]
Also, the fact, that "Whitey" is just a nickname given to a "Carrier" by the community, not by developers themselves, so it's not canon anyway.

**Comment by xerox8521** [comment]
Thats exactly the reason why it comparison doesn't make sense. "Zombie" comes actually from the mod name where as "Whitey" is a community nickname since hes officially called "Carrier".

**Comment by Tabajara77** [comment]
Indeed, community created the nickname "whitey". Even on the survival guide, it always has been the Carrier.
Same thing would be Human VS Zombies; which in the overall it's perfect be: Survivors VS Undead.
