### ISSUE TITLE
[Suggestion / Request] Multiple Suggestions

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#239]
One friend of mine asked me to write down some ideas and suggestions he had regarding the entities.
I don't expect any of these to be actually possible to implement, but still.

Here are some of them:

-Fully functional "func_tank" as in HL2 singleplayer with a way to setup custom sounds like on doors or elevators aka func_tracktrain's.

-New Inputs for "!player" entity "SetPlayerModel" or "SetCustomPlayerModel", which can be executed by the server or maps (There are some good modding purposes for that).

-"respawning time" keyvalue for every item/weapon entity.

-Keyvalue for "random_" type of firearm weapons that can be set to have specific amount of ammo in it. Maybe something like in NMRiH where you can't be sure if the gun is loaded or not.

-prop_ragdoll_multiplayer so the ragdoll physics can be processed only on the client side.

-A brush entity that works like "func_illusionary" but can be setup to be seen only be one of the teams (Like info_beacons do). Other option is setting up the said func_ entity to be seen by specific player(s).

-Fully functional "point_viewcontrol" which can be useful for creating a cutscenes in ZPO maps maybe. This thing might be really useful in some cases.

-A new point entity "game_timer" which will be visualized like a regular timers from ZPA/ZPH gamemodes, but you can actually setup it properly, instead of messing with logic_timer's, game_text and other entities. Might help to save up on entdata.

-Support of team_filters for prop_door_rotating.

-Maybe add a crossbow as a new weapon in the future? Because why not? That might work, right?

**Comment by xerox8521** [comment]
I dont like the SetModel function for players as we would end up with hundres of maps full of random characters and there is actually no good reason to add it anyway.

**Comment by DoofusCockslap** [comment]
Well, it's not my idea once again. The guy who asked me to write that down actually has some ideas how to use that. He did some very good maps for Black Mesa that used custom model settings for players.

**Comment by Tabajara77** [comment]
Alright my opinion and review of the request:
- Like Xerox said, not a fan of that if can be abused and no good reason to be add
- "respawn time" for weapons and ammo should be 480 sec by default code only - I was planning to remove those cheat commands.
- Disagree to add that on ZPS. New guns spawned by the round will be full loaded. Most of the cases, will happen on the middle of the battle if the gun has or not already been used.
- Dunno if is that possible or would save entity memory.
- That could work for zombie team to see where they could go via Zvision; good idea tho.
- game_timer i will leave with Jonny but good idea.
- New weapons we will discuss within the dev team. So no promises.

**Comment by jonnyboy0719** [comment]
**func_tank**
This will not be implemented fully, it will rather be removed. Because its very broken for MP side.

**!player model**
I doubt this will be a thing

**Respawning**
This will never happen, and the old cvars for it has been removed, It is now stuck to 480 seconds like intended.

**Ammo Wep on Spawn**
ditto, as Tabajara stated it.

**Ragdolls**
Ragdolls is already calculated for clients only, but I could check on the prop_ragdoll, no promises tho. It would be best to use as little ragdoll ents as posssible tho imo.

**camera controller**
I know it was fixed on CS:GO, but I could take a look at it. No promises tho.

**game_timer**
I like this idea, I will put it on my bucket list.

**new weapons**
As taba said, no promises.

**Comment by DoofusCockslap** [comment]
Alright guys, thanks for the reviewing this.

**Comment by Tabajara77** [comment]
No worries! Any time.
