### ISSUE TITLE
[Suggestion / Request] "info_player_carrier" entity

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#242]
After watching Casei's last stream I was thinking about one stuff. 
How we can make Carrier spawn in specific area/spot and separate the regular zombie-spawn points from him?

The entity I am suggesting might be useful on some objective maps for various purposes.
It's just a simple zombie spawn, but the only difference is that it is limited to spawn only Carrier. 
It could be setup to be used once i.e, on round start only and then force him to be spawned on regular zombie-spawns. But also may be used to spawn him constantly only at this spawn point (better have multiple of those on map then).

**Comment by jonnyboy0719** [comment]
info_player_carrier is now part of 3.0
