### ISSUE TITLE
[Suggestion / request] panic! buff

### ISSUE THREAD

**Issue by Lt-Aoi** [ZPSNMRiHIssues/zpsissues#244]
Panicking could be very useful if it didn't only recharge your stamina but could also give you a speed boost, because even if you're on panic mode the zombies can still reach you easily, it should at least have a small speed boost, because it only lasts for a low amount of time. (i'm not saying you should increase the time) So why not make the speed a little higher because of the low amount of time you have while panicking?

**Comment by xerox8521** [comment]
Panic is intended to give you a small stamina boost if you are low on stamina. I don't think it should give speed as more people would also abuse it to get guns after round start.

**Comment by jonnyboy0719** [comment]
Panic is only for last minute resort, just like in ZP1, and It won't be buffed.
