### ISSUE TITLE
Aquatica - Elevators Refusing to Restart

### ISSUE THREAD

**Issue by SgtMartin** [ZPSNMRiHIssues/zpsissues#26]
When playing zpo_aquatica (the public build), I will occasionally -- and sometimes quite frequently -- run into a problem where the survivors grab the item from the lab and make it back to the elevators, only for the elevators to never come back online. The round ends with the survivors drowning because they simply cannot progress further.

I've yet to find a way to reproduce this bug. Also, as stated above, this has only been tested in the public build of Zombie Panic! Source.

**Comment by maisteven** [comment]
Interesting... I've experienced the opposite of this on S1gaming. The elevator starts up even if no one gets the item after the barrel explodes. It's happened so many times that the veterans now don't even bother getting the item but instead they rush to the end before the barrel explodes.

**Comment by Cookieandcream** [comment]
I believe its like that in cvg too. I have seen exactly the same thing as flippy. Surviours often skip the "Get the item" objective and rush to the evevators after moving the barrels and end up winning.

**Comment by SgtMartin** [comment]
Thank you for adding that as well, Flippy and Cookie! We also get that bug too, but I was hesitant to report it because I could have sworn we tested for it about a month and a half ago and saw that it was fixed in the dev build. If I am mistaken though, then it definitely needs to be reported/fixed, as it's even more prevalent.
