### ISSUE TITLE
ZPO_Silent Skies- Boxes Prevent From Jumping

### ISSUE THREAD

**Issue by Cookieandcream** [ZPSNMRiHIssues/zpsissues#27]
Boxes like the ones located near "SAS Airlines" have invisible clipping that prevents Survivors/zombies from jumping onto the boxes and the poles beside them. Whereas jumping is possible at the other poles of other airlines. That issue may create a problem when being chased by a zombie especially, when doing the first objective. It seems like you may also get stuck in between them while running away. 

![zpo_silent_skies0015](https://f.cloud.github.com/assets/4086414/354524/0cff9348-a0a2-11e2-9693-fee54f6f1979.jpg)
Running forward, the invisible wall is keeping me from getting onto the box.
![zpo_silent_skies0013](https://f.cloud.github.com/assets/4086414/354525/10b0d880-a0a2-11e2-877e-f6adc9182d3d.jpg)
![zpo_silent_skies0017](https://f.cloud.github.com/assets/4086414/354533/17017c58-a0a2-11e2-8f9a-e557385f3110.jpg)
On this side of the box, the invisible wall extends out further than the boxes. Which prevents you from being able to make a full jump when running beside the boxes.

**Comment by SiggyWiggyWoo** [comment]
True, I'll remove that player clip.
