### ISSUE TITLE
Hitbox problem | ZPS 2.4

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#29]
Players have been complaining about the currently "hitbox" in ZP:S. Maybe hitbox is not correctly worked.
And one guy said that he did a "HS" aiming zombie's feets. Idk if the zombie was lagging or not.

Since i don't understand so much in this area about "hitbox", this thing will be fixed soon or is already fixed in dev build?

**Comment by Smil3yRiley** [comment]
Need more info; what server is it happening on, what are the pings for each player, etc.

**Comment by Tabajara77** [comment]
I have seen one video from a UK server (Players from Europe that plays on that server) and the guy reported this issue showing a video that he tried to do 2 headshoots on two regular zombies, but they didn't died.
This video was uploaded in 2012 from "ZPSBestProfileName"

One video he made : http://www.youtube.com/watch?v=Vm_KPzNWfSk
Other one: http://www.youtube.com/watch?v=2Frv9MkpcaA

Now, i play in a brazilian server and some players is complaing that they made HS but wasn't a real HS to make the zombie die. 

And about the "Hs aiming zombie's feet", i didn't saw it, my friend told me that happened.

**Comment by ghost** [comment]
Lol, i dint want to make a reference to #73 , sorry.

I just recorded a video to proof the delay of the hitboxes:

http://www.youtube.com/watch?v=2K2CCfu-0Q8

As anyone can see, the model is far from the hitbox.

If the player in fact move pretty more fast, i would compare the hitboxes from zps to the ones from half life deathmatch source:

http://www.youtube.com/watch?v=k4bvQDWfWqE
