### ISSUE TITLE
Voice Command Menu covers text chat

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#3]
If you bring up the Voice Command menu, it may block text chat messages that are either really long, or are from people with long Steam names

![2013-04-02_00005](https://f.cloud.github.com/assets/3606650/329932/cfe55726-9bc0-11e2-822e-fb771a17fdc4.jpg)

**Comment by jonnyboy0719** [comment]
Can't be fixed due the voice command frame is front of the chat frame.
