### ISSUE TITLE
Stuck in ATC tower

### ISSUE THREAD

**Issue by Deliux** [ZPSNMRiHIssues/zpsissues#31]
Everyone got stuck in same place, behind computers.
![2013-04-14_00008](https://f.cloud.github.com/assets/3256637/378424/8582bc2a-a53c-11e2-8934-606e1057cc0e.jpg)

Some gliched stairs textures.
![2013-04-14_00007](https://f.cloud.github.com/assets/3256637/378451/cc48d9ee-a53e-11e2-8b5e-c5c1420c2c66.jpg)

**Comment by SiggyWiggyWoo** [comment]
Thanks, fixing those, 2nd one has a too bright reflections, I'll lower it.
