### ISSUE TITLE
Zpo_Silentskies Various Bugs

### ISSUE THREAD

**Issue by DiGSurvivor** [ZPSNMRiHIssues/zpsissues#35]
*Missing floor texture near VIP lounge. 

https://www.dropbox.com/s/9nsieaoxjqhhend/2013-04-14_00001.jpg

*Disappearing fuel can when you switch items fast when dropped.

https://www.dropbox.com/s/atsobyi3jzsow6e/2013-04-14_00002.jpg

https://www.dropbox.com/s/tn61p2128othp0y/2013-04-14_00003.jpg

*Ladder in elevator shaft that goes up to the tower needs to be fixed so people do not have to jump across to get on the ladder. 

 https://www.dropbox.com/s/qohwzfo6uceb70p/2013-04-14_00004.jpg

*People were complaining about getting stuck behind computers in the tower.

 https://www.dropbox.com/s/xu9kuyancorz2f6/2013-04-14_00005.jpg

**Comment by SiggyWiggyWoo** [comment]
Thanks for the reports. Fixing it all but the fuel can, sending that to other devs.
