### ISSUE TITLE
Silent Skies - Climbing Spots

### ISSUE THREAD

**Issue by SgtMartin** [ZPSNMRiHIssues/zpsissues#36]
This first picture is to show the surrounding a bit, so that you know where these can be found at.
![2013-04-14_00002](https://f.cloud.github.com/assets/4086686/378454/0879be38-a53f-11e2-88b6-63dffc97d665.jpg)

One of the spots, on top of a door way.
![2013-04-14_00003](https://f.cloud.github.com/assets/4086686/378455/0bd3a8be-a53f-11e2-9c41-b38cef1189fb.jpg)

The second spot (the zombie) on top of a door itself.
![2013-04-14_00004](https://f.cloud.github.com/assets/4086686/378456/0e73641a-a53f-11e2-957e-72f27f2a4aec.jpg)

Both of these spots were found down in the generator basement, and can be accessed by survivors and zombies alike.

**Comment by SiggyWiggyWoo** [comment]
Thanks, clipping off those spots.
