### ISSUE TITLE
Various invisible things on zpo_blackout

### ISSUE THREAD

**Issue by tylerjames-on** [ZPSNMRiHIssues/zpsissues#37]
The underside of the tables are see through in the tower.
![2013-04-14_00024](https://f.cloud.github.com/assets/4119237/378470/aede36cc-a540-11e2-93bb-8b35453bba9e.jpg)

The little wooden fence thing that surrounds the dirt is paper thin creating a weird illusion.
![2013-04-14_00023](https://f.cloud.github.com/assets/4119237/378471/ba6f6c40-a540-11e2-8327-6073be903a92.jpg)

You can see through the underside of the subway train that you can go inside of.
![2013-04-14_00017](https://f.cloud.github.com/assets/4119237/378475/c9c76fc6-a540-11e2-843a-3fcd1870fdea.jpg)

One of the wrecked subway trains doesn't have a bottom.
![2013-04-14_00015](https://f.cloud.github.com/assets/4119237/378479/0cdcaea2-a541-11e2-95f0-8154fda79010.jpg)

**Comment by Smil3yRiley** [comment]
Can you describe what's happening in each screenshot?

**Comment by tylerjames-on** [comment]
Updated.

**Comment by SiggyWiggyWoo** [comment]
Thanks, fixing all that.
