### ISSUE TITLE
Glitchy Pedro zombie hands

### ISSUE THREAD

**Issue by tylerjames-on** [ZPSNMRiHIssues/zpsissues#38]
![2013-04-14_00003](https://f.cloud.github.com/assets/4119237/378480/356df344-a541-11e2-9a75-9b659486be3c.jpg)

![2013-04-14_00002](https://f.cloud.github.com/assets/4119237/378481/394f9b52-a541-11e2-9dcc-ecae5c511019.jpg)

![2013-04-14_00001](https://f.cloud.github.com/assets/4119237/378483/3be69fe6-a541-11e2-98de-56de67f6f70b.jpg)

I only got this for a few rounds once I first joined, and only as a zombie.

**Comment by Smil3yRiley** [comment]
Were you able to replicate this on silent skies?

**Comment by tylerjames-on** [comment]
No, it appeared a few rounds in a row and then I didn't get it again for a while. Then it came back for a round.
I'm not sure of a way to replicate it.
