### ISSUE TITLE
Strange door behavior (zps_town)

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/zpsissues#4]
This occured when I was playing on zps_town in the S1Gaming server; when I opened the double doors in the School, the window brushes remained in place and were unbreakable

I wasn't able to replicate this later in the later rounds we spent in game

![2013-04-02_00001](https://f.cloud.github.com/assets/3606650/329944/113039a8-9bc1-11e2-88a1-3c16224258f2.jpg)

**Comment by darbdude** [comment]
This only happens to me when i alt tab sometimes, in whatever map with doors. They will appear open when they are closed and vice versa
