### ISSUE TITLE
ZPS rounds take some time to end.

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#48]
Okay this is very, very rare to happen.
When you reach the final human's obj and should work the "End Game" ( Survivors Wins) but it doesn't. It took like 6~10 seconds to end the round, and when it ends, doesn't display the "Survivors Wins", just start another new round.

For example that when i was a zombie, someone was infected, and all were on the final obj. All died and it was supposed to show "Zombies win", but doesn't showed anything for 10 seconds and any humans weren't alived.

**Comment by Wazanator** [comment]
It's due to the infection check, I'll make sure sammy sees this
