### ISSUE TITLE
Non-English (ISO) Characters Problem

### ISSUE THREAD

**Issue by ghost** [ZPSNMRiHIssues/zpsissues#50]
There is a lot of players who does not talk or does not have an english name.

In Portuguese for example, we have some special characters, example: ç ã á à è é ú í ó õ ô â ê

My own name for example is André Gomes de Paiva

so in zps they stay like square blocks, on the player list, hint menus, and even amx-styled menus (like !msay)

Please, let the zps font have the special characters!
maybe this converting-ISO table can help:
http://www.lsi.usp.br/~help/html/iso.html

**Comment by jonnyboy0719** [comment]
special characters from any country (even english special character) will not be drawn by the ZP font, it does not support such characters.
