### ISSUE TITLE
Git-Hub ZPS Page shows secret upcoming features

### ISSUE THREAD

**Issue by ghost** [ZPSNMRiHIssues/zpsissues#52]
Dev-Related bugs (with screenshots) are available here for everyone to see and track.

However, by the screenshots, everyone can come here and see upcoming features like:
- Pedro
- Pipe Wrench
- Etc...

I have not told this for anyone, since i think the zps team work hard for make new content for us players, so i'm reporting this.

**Comment by Smil3yRiley** [comment]
No shit son, it's going to be public soon anyway; if you haven't noticed we accidentally leaked Pedro in our readme.txt (go read it in the zps client.gcf) and you can look further around in YouTube

We still have some neat surprises that we aren't posting here =P
