### ISSUE TITLE
Texture missing on zps_industry

### ISSUE THREAD

**Issue by TheCimeran** [ZPSNMRiHIssues/zpsissues#57]
![2013-04-21_00001](https://f.cloud.github.com/assets/4086350/406870/d41842c6-aac1-11e2-8aad-a75284799fdf.jpg)
There was a texture missing at the entrance of the map. As of yet I can't figure how to download from steam cloud since it is down. As soon as it is up and running I will attach.

**Comment by Wazanator** [comment]
Fixed, forgot to upload texture
