### ISSUE TITLE
zpo_silentskies various minor bugs

### ISSUE THREAD

**Issue by Xufe** [ZPSNMRiHIssues/zpsissues#59]
First one : Nodraw texture located at elevator at top floor

![2013-04-21_00015](https://f.cloud.github.com/assets/4218595/406849/ea740740-aac0-11e2-9e2e-8179712bb93d.jpg)

Fps problem :
![2013-04-21_00014](https://f.cloud.github.com/assets/4218595/406852/0fdd8934-aac1-11e2-9d4d-bbc3f95340c9.jpg)

FPS problem at ramming objective
![2013-04-21_00013](https://f.cloud.github.com/assets/4218595/406854/1f835b48-aac1-11e2-92d8-dc176f413087.jpg)

Bloody hands are not realistic

![2013-04-21_00012](https://f.cloud.github.com/assets/4218595/406855/2e8c9c4e-aac1-11e2-996f-11231cc610ab.jpg)

Reflection bug, reflections look stupid
![2013-04-21_00011](https://f.cloud.github.com/assets/4218595/406858/3d43aef8-aac1-11e2-897b-cd69951c7017.jpg)

Not enlighted props at the side of generator
![2013-04-21_00010](https://f.cloud.github.com/assets/4218595/406859/4b728378-aac1-11e2-8aa7-c1a6747ae57b.jpg)

Sparks are detached , they spawn from nowhere
![2013-04-21_00005](https://f.cloud.github.com/assets/4218595/406861/5cc2fad6-aac1-11e2-8978-0503f031d4dc.jpg)

Train wreck: Inside not textured
![2013-04-21_00006](https://f.cloud.github.com/assets/4218595/406862/65f30cb8-aac1-11e2-9aa5-aa95f22c0588.jpg)
![2013-04-21_00007](https://f.cloud.github.com/assets/4218595/406864/70eb099a-aac1-11e2-8382-52523d3bc61d.jpg)

Stair Handrail not  attached right
![2013-04-21_00008](https://f.cloud.github.com/assets/4218595/406865/7d7810d6-aac1-11e2-8d3e-e2ece314c612.jpg)

**Comment by SiggyWiggyWoo** [comment]
Thanks, fixed it all up.
