### ISSUE TITLE
Hitboxes have a big delay 

### ISSUE THREAD

**Issue by ghost** [ZPSNMRiHIssues/zpsissues#76]
I just recorded a video to proof the delay of the hitboxes:

http://www.youtube.com/watch?v=2K2CCfu-0Q8

As anyone can see, the model is far from the hitbox.

If the player in fact move pretty more fast, i would compare the hitboxes from zps to the ones from half life deathmatch source:

http://www.youtube.com/watch?v=k4bvQDWfWqE

I'm gonna record another video shooting and update the issue.

**Comment by Tabajara77** [comment]
Duplicated https://github.com/ZPSNMRiHIssues/zpsissues/issues/29
Post theses videos on that link issue.
