### ISSUE TITLE
zpo_silent skies door bug

### ISSUE THREAD

**Issue by tylerjames-on** [ZPSNMRiHIssues/zpsissues#78]
![2013-05-12_00007](https://f.cloud.github.com/assets/4119237/493329/88622018-bb38-11e2-913a-570cc1497055.jpg)

So if you stand far enough back from this doorway, the map behind it disappears and you see through it.

**Comment by SiggyWiggyWoo** [comment]
Thanks, fixing that.

**Comment by Smil3yRiley** [comment]
That's an area portal issue, and the ticket could've used a better description like "(zpo_silent_skies) Odd visual glitch by VIP Lounge door"!
