### ISSUE TITLE
zpo_silent_skies train glich

### ISSUE THREAD

**Issue by Deliux** [ZPSNMRiHIssues/zpsissues#79]
If you push beam under the train like this, train will stuck and round goes bad... And after round end in other round everyone will hear train ambient sound or something like that.
![2013-05-12_00002](https://f.cloud.github.com/assets/3256637/493394/054eb53a-bb40-11e2-9133-408e569d525d.jpg)

**Comment by SiggyWiggyWoo** [comment]
Thanks, I'll block it so that won't be possible, and fixing that train sound for sure next time.

**Comment by Smil3yRiley** [comment]
Use proper spelling and take the time to give your tickets a better description: This ticket could've been titled "(zpo_silent_skies) You can block the train with physics props"

**Comment by Deliux** [comment]
Will try better next time, sorry :/
