### ISSUE TITLE
Create A Server Bug

### ISSUE THREAD

**Issue by DiGSurvivor** [ZPSNMRiHIssues/zpsissues#8]
So I just got the ZPS Dev Build back up and running on my computer and I wanted to make sure that it was running ok. I noticed that if I tried to create my own server whether or not it was in test mode, that once I tried to pick a team the entire game would crash; however, when I connect to our PT server I am able to join a team and it gives me the awaiting more players screen. Do not know if this is just me or everyone.

**Comment by Smil3yRiley** [comment]
Thanks for the first ticket, but can you check if this occurs in the public build too

(also leakz!)

**Comment by DiGSurvivor** [comment]
It does not occur in my public build.
