### ISSUE TITLE
zpo_silentskies various minor bugs #2

### ISSUE THREAD

**Issue by Xufe** [ZPSNMRiHIssues/zpsissues#80]
![2013-05-12_00001](https://f.cloud.github.com/assets/4218595/493387/c19f1f3c-bb3f-11e2-859d-5c7172b6294a.jpg)
Overlapping textures causing flickering ( Basement at generator)

![2013-05-12_00002](https://f.cloud.github.com/assets/4218595/493389/d4f3f346-bb3f-11e2-9bc1-8939fca10343.jpg)

The taxi  crashed into the lamppost, yet the fancy  paperline din't get damaged... like a baws...

![2013-05-12_00003](https://f.cloud.github.com/assets/4218595/493390/edf396a8-bb3f-11e2-9115-da2c42b60d31.jpg)
Texture missing on top of door frames at human spawn

![2013-05-12_00004](https://f.cloud.github.com/assets/4218595/493392/fec71c84-bb3f-11e2-83af-5db06e7eb883.jpg)
What is this thing for, a wannabe-stair ?

![2013-05-12_00005](https://f.cloud.github.com/assets/4218595/493396/11d61a1e-bb40-11e2-8bcd-7166faa0a660.jpg)
Some of these palnts are solid while others are not

![2013-05-12_00006](https://f.cloud.github.com/assets/4218595/493397/2262f730-bb40-11e2-8649-fe0107b35a5d.jpg)
Whoever wrecked all these beautiful tiles for this stair... should get  NO COOKIES NEVER

![2013-05-12_00009](https://f.cloud.github.com/assets/4218595/493403/3fc5a4d0-bb40-11e2-9976-f4a256b77d66.jpg)
There is no water proof floor in this  spring...

![2013-05-12_00011](https://f.cloud.github.com/assets/4218595/493404/5169de2c-bb40-11e2-9a98-c7d5872b69b0.jpg)
Missing texture at zombie spawn.

**Comment by SiggyWiggyWoo** [comment]
Thanks, fixing it all.

**Comment by Smil3yRiley** [comment]
Try to use a more descriptive title in your tickets, in this case this ticket is predominately comprise of texture and brush alignment issues, the ticket should reflect that as something like "zpo_silent_skies: Issues with Textures and Brushwork Part 3" or something!
