### ISSUE TITLE
New Zombievision bugs with some statics

### ISSUE THREAD

**Issue by Xufe** [ZPSNMRiHIssues/zpsissues#81]
The New Zombievision still bugs with some static, don't know what causes the problem yet im just giving pictures.
![2013-05-12_00008](https://f.cloud.github.com/assets/4218595/493407/93ecc37c-bb40-11e2-9a81-57e3a41fbd33.jpg)
![2013-05-12_00007](https://f.cloud.github.com/assets/4218595/493408/946a8ec4-bb40-11e2-9332-ed0e77a3b808.jpg)

**Comment by Smil3yRiley** [comment]
By "statics" you mean "Static Props", please take the time to write out the full description of whatever issue you find =P
