### ISSUE TITLE
zpo_silentskies - Wrong computer's light to hack 

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#82]
The correct one was on my left, but the light was on the other computer.
![2013-05-12_00001](https://f.cloud.github.com/assets/4042019/493416/6cfc7892-bb41-11e2-8f97-bdc7e3baa1db.jpg)
At "SAU" area.
![2013-05-12_00002](https://f.cloud.github.com/assets/4042019/493417/7875e87a-bb41-11e2-830a-d31a635da8b1.jpg)

**Comment by SiggyWiggyWoo** [comment]
Thanks, fixing that.

**Comment by Smil3yRiley** [comment]
On a related note, please use proper grammar in your tickets, you can take a few seconds to type out "Silent" without butchering the spelling
