### ISSUE TITLE
Zpo_Silent_Skies Bugs

### ISSUE THREAD

**Issue by TestWolf** [ZPSNMRiHIssues/zpsissues#83]
![2013-05-12_00001](https://f.cloud.github.com/assets/4411628/493431/63249b36-bb43-11e2-8917-ff90301183cd.jpg)
When i point my flashlight and that kind of props i get that wierd effect on it
![engine](https://f.cloud.github.com/assets/4411628/493433/7d39f0ca-bb43-11e2-9104-873523813a7b.png)
I was walking around the map and then the zps dev build crashed with this engine error

**Comment by SiggyWiggyWoo** [comment]
Thanks, should be fixed in the next test, if it isn't please tell me.

**Comment by TestWolf** [comment]
No problem, i will let you know

**Comment by Smil3yRiley** [comment]
Use a better descriptive in your ticket title, "zps_silent_skies_ Bugs" is so generic
