### ISSUE TITLE
Crash on zpo_silentskies

### ISSUE THREAD

**Issue by TheCimeran** [ZPSNMRiHIssues/zpsissues#84]
Crash file: http://www.filedropper.com/hl24104crash2013512t194239c0

I was on the train when the lights went out and I guess the nukes were going off. I had my flashlight out and when it said zombies win I crashed...

hope this is helpful

**Comment by SiggyWiggyWoo** [comment]
Thanks, I'll see if I can do something about that.

**Comment by Smil3yRiley** [comment]
Bug sammy about it too, he should be able to look at the crash dump
