### ISSUE TITLE
Request - IED Icon Kill

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#85]
The IED should have a special icon kill when you kill someone with it.
The currently one just shows a skull
![2013-05-07_00001](https://f.cloud.github.com/assets/4042019/499317/b1bfa1a4-bc39-11e2-8fa0-1ee93a94d604.jpg)
![2013-05-07_00002](https://f.cloud.github.com/assets/4042019/499316/b1604cb8-bc39-11e2-9616-215b59290c05.jpg)

**Comment by Smil3yRiley** [comment]
We already have a custom icon for the IED killfeed (located in resource\fonts\zpdeath.ttf) but for some reason it's not using it
