### ISSUE TITLE
zpa_town round does not end

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#87]
On zpa_town if survivors could keep the entire 5-6 minutes the Capture Point and the Timer switches to "Over Time" the round does not end untill all survivors are killed and zombies take over the checkpoint which leads to a "Zombie win". Its almost every round if survivors can defend the Capture Point

Edit: Also Spectators in Lobby are frozen once the round started

**Comment by Smil3yRiley** [comment]
Duplicate of https://github.com/ZPSNMRiHIssues/zpsissues/issues/7
