### ISSUE TITLE
zps_deadend playerclips ( not all)

### ISSUE THREAD

**Issue by Xufe** [ZPSNMRiHIssues/zpsissues#88]
There are a lot of areas that need palyerclip fixes. doorframes i.e or the  mising playerclip at the human spawn fence...

![2013-05-19_00014](https://f.cloud.github.com/assets/4218595/523507/e4bd9022-c0bf-11e2-8574-2c931aa6589b.jpg)
![2013-05-19_00006](https://f.cloud.github.com/assets/4218595/523508/e4d986ba-c0bf-11e2-9898-aa5842d1f06f.jpg)
![2013-05-19_00007](https://f.cloud.github.com/assets/4218595/523509/e4f59918-c0bf-11e2-925b-93f38a0772db.jpg)
![2013-05-19_00002](https://f.cloud.github.com/assets/4218595/523510/e4f78c3c-c0bf-11e2-9466-d2d1c876bf75.jpg)
![2013-05-19_00001](https://f.cloud.github.com/assets/4218595/523511/e4f94630-c0bf-11e2-9122-702d0733da52.jpg)
![2013-05-19_00005](https://f.cloud.github.com/assets/4218595/523512/e4fbf678-c0bf-11e2-9876-d3e148199355.jpg)
![2013-05-19_00004](https://f.cloud.github.com/assets/4218595/523513/e4ff0192-c0bf-11e2-9cec-2dac25af2074.jpg)
![2013-05-19_00003](https://f.cloud.github.com/assets/4218595/523514/e5043b62-c0bf-11e2-8a2a-3760a08193c1.jpg)
![2013-05-19_00008](https://f.cloud.github.com/assets/4218595/523515/e510aea6-c0bf-11e2-87db-b49172ce7e3d.jpg)
![2013-05-19_00009](https://f.cloud.github.com/assets/4218595/523516/e513101a-c0bf-11e2-9ad3-56dc32e38fe5.jpg)
![2013-05-19_00010](https://f.cloud.github.com/assets/4218595/523517/e51568d8-c0bf-11e2-9bb0-ab7d4e60f011.jpg)
![2013-05-19_00011](https://f.cloud.github.com/assets/4218595/523518/e517a148-c0bf-11e2-844f-0307d7f4c07e.jpg)
![2013-05-19_00012](https://f.cloud.github.com/assets/4218595/523519/e51b464a-c0bf-11e2-8d92-091d86259824.jpg)
![2013-05-19_00013](https://f.cloud.github.com/assets/4218595/523520/e521837a-c0bf-11e2-89b1-8e009ea4e5cd.jpg)

Generally you should check for 1-4  inches wide sptos where you can get caught in, basically anything above 4 is not worth playerclipping.

**Comment by Smil3yRiley** [comment]
What is this ticket about? Is it about the pre-existing player clips? Or are you suggesting to add more? Please use a better description next time

And if you want to show us playerclips, use this command in your developer console: 
r_drawclipbrushes 1

**Comment by Xufe** [comment]
Waz said I should make screenshots for the palyerclips.. I think its somewhat unnessecary as a mapper should know where to place playerclips...

but you are right a better description would have been nice

**Comment by Tabajara77** [comment]
Most of them have been fixed.

_Closed_
