### ISSUE TITLE
Lag when I looking around

### ISSUE THREAD

**Issue by Billychan1997** [ZPSNMRiHIssues/zpsissues#89]
My system specs:
System:Window 7 32bit
GPU:Nvidia Geforce Gt9800
CPU:Intel(R) Core(TM)2 Quad CPU Q8200 @ 2.33GHz 2.34GHz
RAM:4 GB RAM DDR2

When I looking around in the game , my fps in 100 >20~10.
Also,when I move my mouse very fast in game background, the background music will be Lag.

**Comment by Smil3yRiley** [comment]
First off, what level were you on? Secondly, what were your video settings? Thirdly, were you just standing around or were you fighting zombies? Without information like this, this ticket is essentially useless

**Comment by Billychan1997** [comment]
I uninstalled my Geforce drive and reset my video settings
The problem is already fix.
Thank for leaving commented.
