### ISSUE TITLE
Console Weapons Errors

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#9]
This happens on console servers since ZPS 2.0 

Error reading weapon data file for: weapon_slam
Error reading weapon data file for: 
and
Attempted to create unknown entity type weapon_hammer!
Can't init weapon_hammer

**Comment by BreakinBenny** [comment]
I believe the weapon_slam is a supposed leftover of the IED reusing the entity, while weapon_hammer was clearly for the removed hammer weapon.

I can confirm that the weapon_slam entity can be spawned if you extract the weapon_slam.txt from HL2 Deathmatch's VPK to ZPS' scripts folder.
