### ISSUE TITLE
Zombies can do Headshots

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#90]
Uhm, for some reason is it possible for the zombies (with a very low chance) to kill survivors with a headshot. On the Server im playing on uses a Sound which plays if there was a headshot. Now sometimes it can happen you get killed as a survivor with hearing the Headshot sound and no im not killing a zombie at the same time while he killed me.

**Comment by Tabajara77** [comment]
Correct. On my server, i killed a human and the GameME said it was a headshot.

**Comment by Wazanator** [comment]
I believe at the moment you can get a headshot as a zombie however you do not get the bonus damage.

**Comment by Smil3yRiley** [comment]
Zombies can do headshots, ATM we haven't added a damage multiplier (haven't decided if we want to)
