### ISSUE TITLE
zps_ruralpanic public build clipping issues

### ISSUE THREAD

**Issue by GunF0x** [ZPSNMRiHIssues/zpsissues#92]
Just a few minor areas around zombie spawns that I noticed several newer players struggle with. Seems crouch jumping is very hard for them, and they have trouble getting out of the horse stall without an open door.
http://tinypic.com/m/fxukid/1

 And an area that is very easy to get stuck in when dismounting a ladder in white house, gets you stuck on ceiling. Circled in red.

http://tinypic.com/m/fxukih/1

**Comment by Smil3yRiley** [comment]
Thanks for the ticket

BTW you can simply just drag and drop your images into the ticket, makes it easier to see issues that way
