### ISSUE TITLE
zpo_aquatica - elevator and cart glitch

### ISSUE THREAD

**Issue by neoassassin** [ZPSNMRiHIssues/zpsissues#94]
![zpo_aquatica0008](https://f.cloud.github.com/assets/4086419/597000/2490ed78-cbd0-11e2-9446-4b947fa7936d.jpg)
If you stand in the doorway of the elevators, you get slightly pushed up. Which can interfere with gameplay by keeping you from moving for a second.

![zpo_aquatica0009](https://f.cloud.github.com/assets/4086419/596997/f01fb1be-cbcf-11e2-9618-bdce8ff5b8a0.jpg)
![zpo_aquatica0010](https://f.cloud.github.com/assets/4086419/596998/11f56568-cbd0-11e2-8113-73145575c75d.jpg)
You can get people stuck in the wall with the cart in lab. If they stand behind the handle they will get stuck in the door, and have to be teleported somewhere. In this case he was teleported into the door and remained stuck there.

**Comment by SiggyWiggyWoo** [comment]
Thanks, I'll see what I can do.
