### ISSUE TITLE
Wrong " I need ammo message"

### ISSUE THREAD

**Issue by DarkTanner** [ZPSNMRiHIssues/zpsissues#98]
Sometime the targeted weapon is not good

**Comment by Smil3yRiley** [comment]
Can you give me a more detailed example? What's happening when the issue appears?

Also, sorry for the late response!

**Comment by JoelTroch** [comment]
Sometimes the sentence is cut in half :

Instead of having : (VOICE) ~_L-M_~-/TFH-Shepard (Linux <3) : I need ammo!
We have something like : (VOICE) ~_L-M_~-/TFH-Shepard (Linux <3) : ammo!

**Comment by Tabajara77** [comment]
Correct. The Voice doesn't give the "weapon type" in the "chat area", it just shows " ammo. ".
Should be "Need pistol ammo."

**Comment by Tabajara77** [comment]
![2013-08-28_00001](https://f.cloud.github.com/assets/4042019/1046510/7a6b0a4a-103f-11e3-9921-f595fae993b3.jpg)
Example.

**Comment by jonnyboy0719** [comment]
Fixed on SDK 2013 version.
